### ISSUE TITLE
[FEATURE REQUEST] Maintain order of the Firebase AutoLoad

### ISSUE THREAD

**Issue by TheDuckCow** [GodotNuts/GodotFirebase#270] opened 2021-11-22 05:35 UTC
**Is your feature request related to a problem? Please describe.**
The Fireabse autoload is forced to always be last out of all autoloads, because it is always programmatically added even if it existed previously in the project. I have an issue where my file always loads with errors, which also messes with exporting and running tests from cli, simply due to the AutoLoad for Firebase always being last. The game itself works fine, it's just the initial load.

**Describe the solution you'd like**
Something that preserves my intentional choice of ordering of the auto load. See below:

<img width="873" alt="godot-firebase-autoloads" src="https://user-images.githubusercontent.com/2958461/142805856-7968c400-b9a7-4b65-91b2-173e5c821583.png">

**Describe alternatives you've considered**
I've tried manually editing the `project.godot` file to put it in the order I want, as well as using the up/down arrows to order the autoload in the project settings UI. That indeed works for the *next* Godot reload, however once the project starts up it will reset the order of AutoLoads again, thus making the following reload not work (due to prior autoloads referencing Firebase).

**Comment by TheDuckCow** [comment] 2021-11-22 05:40
To add some details, see the below errors I see on startup. Copying the whole thing just to be explicit, but yes this is referencing many of my own files where I'm trying to reference the AutoLoad. I could make many of these go away by loading in the instance manually, but then it's a different object vs the autoload.

```
Godot Engine v3.4.stable.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
 res://network/session_updater.gd:80 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://network/firebase_login.gd:45 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://network/firebase_login.gd:45 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://tests/network/firebase_login_test.gd:7 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://network/session_updater.gd:80 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://state/session.gd:17 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://network/firebase_login.gd:45 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://screens/menus/dev_scene_select.gd:69 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/database/reference.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/database/database.gd:42 - Parse Error: The class "FirebaseDatabaseReference" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/firestore/firestore_task.gd:106 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firestore/firestore_collection.gd:38 - Parse Error: The class "FirestoreTask" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firestore/firestore.gd:108 - Parse Error: The class "FirestoreCollection" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/auth/auth.gd:182 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/storage/storage.gd:151 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/dynamiclinks/dynamiclinks.gd:41 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/functions/functions.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firebase/firebase.gd:19 - Parse Error: The class "FirebaseAuth" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/auth/auth.gd:182 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/storage/storage.gd:151 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/dynamiclinks/dynamiclinks.gd:41 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/functions/functions.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://network/session_updater.gd:80 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://state/session.gd:17 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Script does not inherit a Node: res://state/session.gd.
 editor/editor_autoload_settings.cpp:488 - Condition "!info->node" is true. Continuing.
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/database/reference.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/database/database.gd:42 - Parse Error: The class "FirebaseDatabaseReference" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/firestore/firestore_task.gd:106 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firestore/firestore_collection.gd:38 - Parse Error: The class "FirestoreTask" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firestore/firestore.gd:108 - Parse Error: The class "FirestoreCollection" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/auth/auth.gd:182 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/storage/storage.gd:151 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/dynamiclinks/dynamiclinks.gd:41 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/functions/functions.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firebase/firebase.gd:19 - Parse Error: The class "FirebaseAuth" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/auth/auth.gd:182 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/storage/storage.gd:151 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/dynamiclinks/dynamiclinks.gd:41 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/godot-firebase/firebase/firebase.tscn' is already being loaded. Cyclic reference?
 res://addons/godot-firebase/functions/functions.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firestore/firestore_task.gd:106 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/firestore/firestore_collection.gd:38 - Parse Error: The class "FirestoreTask" couldn't be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/godot-firebase/database/reference.gd:136 - Parse Error: The identifier "Firebase" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
```

**Comment by WolfgangSenff** [comment] 2021-11-22 11:18
This must be a bug in your Godot. I'm not sure why it would be doing this, but it doesn't do it for any of my projects. Here's an example of one that remains in the correct order at all times. We do nothing regarding the order of Firebase, and have no control over it - I recommend submitting this bug report to the Godot team itself. I'll leave this open for a little bit while checking out some stuff, but 99.99% certain there isn't anything wrong with the plugin.

![image](https://user-images.githubusercontent.com/148612/142852386-d2430f76-33ce-44c8-9a65-0df64d601369.png)

**Comment by WolfgangSenff** [comment] 2021-11-22 14:24
Okay, talked to the Godot team - looks like this may be a bug in Godot, and if you can produce a viable minimum reproduction project and send it to them, they'll look into it. Note that I still do not have this happen with mine above, so I'm not sure what's going on at all - but we did discuss how it might be coming about for others and it seems there could be a reasonable chance it could be fixed by the Godot team.

**Closed by WolfgangSenff** 2021-11-22 14:24 UTC
Labels: enhancement

**Comment by TheDuckCow** [comment] 2021-11-23 02:50
Thanks for going the extra mile connecting with the Godot team! I wonder if it was introduced with 3.4 as I recently switched to using this, I'll see if it occurs in 3.3 and report back here (ack for this being closed in the meantime).

Do you have a thread/topic where you posted this for Godot itself, so I can reply there?

**Comment by TheDuckCow** [comment] 2021-11-23 05:51
After a bit of time trying to replicate the issue, I've narrowed it down to being oddly enough an issue with the WAT testing addon, rather than with Godot itself; the issue arises only when the WAT plugin is enabled, and ceases when disabled. See above referenced issue if curious.
