### ISSUE TITLE
Facebook auth failed

### ISSUE THREAD

**Issue by M77mdsD** [GodotNuts/GodotFirebase#339] opened 2023-05-15 22:33 UTC
**Describe the bug**
Trying to use `Firebase.Auth.get_auth_localhost(Firebase.Auth.get_FacebookProvider())` to login using Facebook but it doesn't work.

**Expected behavior**
`Firebase.Auth.get_auth_localhost(Firebase.Auth.get_FacebookProvider())` Should open a working page to login (this part works) but after that, I get redirected to http://localhost:5000/ with the error "localhost refused to connect." Also, sometimes it works but I get an error message in Godot.

**Screenshots**
![bandicam 2023-05-16 01-31-15-565](https://github.com/GodotNuts/GodotFirebase/assets/65685273/9d175a95-a228-40ae-9c4b-0573c5ec1033)
![bandicam 2023-05-16 02-54-59-114](https://github.com/GodotNuts/GodotFirebase/assets/65685273/4b75cd0a-f9c1-4d30-9dde-8f4c2e58fe6d)

**Environment:**
 - OS: [Windows 11]
 - Browser [e.g. chrome]
 - Godot Version: 3.x (?)

**Additional context**
The login screen opens but after that, the redirect link doesn't work (the profile doesn't get registered in The Firebase users).
Did I miss a setting somewhere?

**Comment by fenix-hub** [comment] 2023-05-16 07:21
Hi, thank you for reaching out.
Could you please share your Firebase and Facebook OAuth2 configurations?
Blur out all the client_id and client_secrets, I just would like to see if everything is correct both in the GodotFirebase .env file and your Facebook application.

**Comment by M77mdsD** [comment] 2023-05-16 14:08
I printed `auth` before the breakpoint and it is an empty dictionary.

**Comment by M77mdsD** [comment] 2023-05-17 00:36
I putted a breakpoint in [L400](https://github.com/GodotNuts/GodotFirebase/blob/c2b6a0952fe57c1e1de23e47dcb59344b64a1c23/addons/godot-firebase/auth/auth.gd#L400) and a `response_code = 400` and the json results was an error: ```
"message": Invalid verification code format.
"type": OAuthException.
"code": 100.
"fbtrace_id": As#####################.
```

**Comment by fenix-hub** [comment] 2023-05-17 10:52
I'm testing and cannot reproduce the error.
Are you sure you are running using the version on `main` branch?
Are the facebook id and secret the correct ones?

**Comment by M77mdsD** [comment] 2023-05-17 12:33
Yeah, can it be something in the Facebook app itself? Should I use a test app or a normal app?

**Comment by fenix-hub** [comment] 2023-05-18 11:26
We don't have our "*official*" guide yet, but basically you can just follow this article since 99% of the stuff that should be configured is not specifically related to our plugin, but general Firebase and OAuth2 flow. 👉 [guide](https://medium.com/litslink/firebase-facebook-sign-in-method-20571606c889)
The only thing you need to do in your project is to set up the `facebook_id` and `facebook_secret` in your `godot-firebase/.env` file like this
```.env
[firebase/environment_variables]
apiKey="xxx"
authDomain="xxx"
databaseURL="xxx"
projectId="xxx"
...

[firebase/auth_providers]
facebook_id="xxx"
facebook_secret="xxx"
```
And everything should just work fine.
Of course feel free to reach us out on discord to get some help.

**Comment by phil-hudson** [comment] 2023-06-30 05:37
Instead of hitting localhost, what happens if you change it to 127.0.0.1?

I'm having issues where my firebase emulator cannot be resolved from godot, and changing the GodotFirebase code from localhost to 127.0.0.1 made it work for me.

**Comment by fenix-hub** [comment] 2023-06-30 06:56
> Instead of hitting localhost, what happens if you change it to 127.0.0.1?
> 
> I'm having issues where my firebase emulator cannot be resolved from godot, and changing the GodotFirebase code from localhost to 127.0.0.1 made it work for me.

If it works for you, that's ok. There's should me no issue about changing from localhost to 127.0.0.1.
Eventually your `hosts` file doesn't map 127.0.0.1 to localhost, or Godot is unable to resolve it.

**Comment by phil-hudson** [comment] 2023-06-30 07:24
Correct, it needs to be mapped in hosts correctly. I just wondered if the user might be having the same issue.

**Comment by fenix-hub** [comment] 2023-06-30 16:35
> Correct, it needs to be mapped in hosts correctly. I just wondered if the user might be having the same issue.

As it happened for you, there might be a chance a user may have the same issue, even if very low.

**Comment by WolfgangSenff** [comment] 2024-05-27 11:59
There's something much bigger here. The entire OAuth2 flow is fully broken now due to deprecations on the Firebase side, removing the loopback URLs in addition to the original URL style. I'm actually going to close this, and when I have a moment, open an entirely new bug to track the issue.

**Closed by WolfgangSenff** 2024-05-27 11:59 UTC
Labels: bug
