### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smyrgeorge** [GodotNuts/GodotFirebase#194] opened 2021-05-20 12:46 UTC
**Describe the bug**
Realtime database updates seems to not work.
I tried several things but i couldn't make it work properly.
The problem seems to be with the fetching data mechanism.
FirebaseDatabaseReference.push, FirebaseDatabaseReference.update are working properly.

**To Reproduce**
- Connect to the root of the database (`test`).
```
var listener = Firebase.Database.get_database_reference("test", { })
```
- Connect to signals.
```
listener.connect("patch_data_update", self, "_on_database_update")
listener.connect("new_data_update", self, "_on_database_update")
```
- Then update a property from firebase console.

**Expected behavior**
My expectation was that after an update in firebase console, i should receive an update in my code.
```
func _on_database_update(data) -> void:
	print(data)
```

**Environment:**
 - OS: Mac

**Additional context**
Update and push seem to working fine.

**Comment by WolfgangSenff** [comment] 2021-05-20 12:50
Can't say with certainty without seeing your setup, but this could easily just be an issue with updating in a place that isn't being tracked. You have to update it at the same level. Firebase only triggers updates for certain things. This should definitely work, and I'll be attempting to reproduce it very shortly, just asking to double-check it to make sure you are getting stuff in the right place. Basically, if update and push are working, then changing it in the console should work just fine too, so long as your setup is correct. I'll test, meanwhile!

**Comment by AmitNanda42** [comment] 2021-05-22 08:36
yes I face the same problem it never gets update. I also like to add calling the function "listener.get_data()" crashes the program.

**Comment by WolfgangSenff** [comment] 2021-05-22 12:33
To update you folks! @smyrgeorge @AmitNanda42 

I believe you've found a bug in Firebase itself. I've been looking into this, and it is sending "put" updates back, not "patch" updates. That means it is miscategorizing the updates and it in turn causes very bizarre things to happen in our plugin. I will be contacting Firebase about this to see if they agree that the issue is theirs. I'll leave this open until (and unless) I hear back, but know that there's nothing immediately that we can do about this bug, because we cannot distinguish between whether or not an update is supposed to be new data or patched data. (Patching is their term for changing data that exists and is already there.)

**Comment by WolfgangSenff** [comment] 2021-05-27 11:26
Okay, unfortunately I have some bad news! Apparently the Firebase team knows about this issue and has been unwilling to fix it. It works differently with the web-based API from the REST API, and they will have to prioritize it. For now, we'll either have to find a work-around, or I just suggest updating from code, which should work I believe. In any case, as this doesn't represent a bug in our library, I'm going to close this issue - if you feel like we should attempt a work-around, we can, and please re-open the issue if you do. Just know that it will take us quite some time to get to the bug.

**Closed by WolfgangSenff** 2021-05-27 11:26 UTC
Labels: bug
