### ISSUE TITLE
Error in the function get_doc in Godot 4.0.3

### ISSUE THREAD

**Issue by minadaniel** [GodotNuts/GodotFirebase#377] opened 2024-01-08 16:50 UTC
Hi, this is my first time here and sorry if this problem has been fixed before but I searched before posting it here.

I activated anonymous login on firebase for my project and I created a collection named cities.

In my application, I wrote this for anonymous login as in wiki Firebase.Auth.login_anonymous(), then inside signup_succeeded(auth_info: Dictionary) function, I emit other signal to begin loading data named load_data and connect it to another scene. This function worked properly when I tested it by printing auth_info. 

Inside other scene I defined my collection then wrote get_doc
```
@onready var collection : FirestoreCollection = Firebase.Firestore.collection('cities')
collection.get_doc('الأقصر')
![Screenshot_20240108-183651~2](https://github.com/GodotNuts/GodotFirebase/assets/13849568/b994ba8d-88df-4ed1-9fcf-a5d7d09fcd3b)

```

Then I got this error:
[Firebase Error] >> Action in error was: 0
[Firebase Error] >> Missing or insufficient permissions.

How to fix this?

**Comment by WolfgangSenff** [comment] 2024-01-08 16:58
It looks just like another issue that was just posted and fixed. The problem is with your rules in Firestore. See this for more: https://github.com/GodotNuts/GodotFirebase/issues/376 I'll go ahead and close this, feel free to re-open if you find this doesn't fix your issue.

**Closed by WolfgangSenff** 2024-01-08 16:58 UTC

**Comment by minadaniel** [comment] 2024-01-08 18:46
In the rules, allow read write is already written not get as in the issue you mentioned
